# These are supported funding model platforms

github: CloneTV
patreon: CloneTV
open_collective: CloneTV
ko_fi: CloneTV
tidelift: maven/VLC-TV-Remote
community_bridge: VLC-TV-Remote
liberapay: CloneTV
issuehunt: CloneTV
otechie: CloneTV
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
