package ru.ps.vlcatv.utils.db;

public class ConstantDataDb {
        public static final int BaseVersion = 2;
        public static final String[] FieldCount = { "count_group", "count_item" };
        public static final String[] BaseCleanSuffix = new String[] {
                "ToDb",
                "ViewCard"
        };
        public static final String[] BaseCreate = new String[] {
                //
                "CREATE TABLE IF NOT EXISTS `TablePlayList` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`updates` TEXT, `creates` TEXT, `unique_root` TEXT );",

                "CREATE TABLE IF NOT EXISTS `TableGroups` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ON CONFLICT IGNORE, `id_parent` INTEGER," +
                        "`crc` INTEGER, `type` INTEGER, `season` INTEGER, `episodes` INTEGER, `total_time` INTEGER, `title` TEXT, `desc` TEXT, `poster` TEXT, `trailer` TEXT, `rating` TEXT, `date` TEXT, `nfo` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableGroups_nfo` ON `TableGroups` (`id_parent`, `nfo`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableGroups_id_parent` ON `TableGroups` (`id_parent`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableGroups_nfo` ON `TableGroups` (`nfo`);",

                "CREATE TABLE IF NOT EXISTS `TableItems` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`crc` INTEGER, `type` INTEGER, `type_online` INTEGER, `rating` TEXT, `awards` TEXT, `season` INTEGER, `episode` INTEGER, `title` TEXT, `desc` TEXT, `poster` TEXT, `trailer` TEXT, `uri` TEXT, `nfo` TEXT, `date` TEXT, `dimension` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItems_uri` ON `TableItems` (`uri`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableItems_id_parent` ON `TableItems` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableItemEdit` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`db_id` INTEGER, `vlc_id` INTEGER, `title` TEXT, `date_add` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItemEdit_id_parent` ON `TableItemEdit` (`id_parent`);",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItemEdit_title` ON `TableItemEdit` (`title`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableItemEdit_db_id` ON `TableItemEdit` (`db_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableItemEdit_vlc_id` ON `TableItemEdit` (`vlc_id`);",

                "CREATE TABLE IF NOT EXISTS `TableItemStatistic` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`time_bool` INTEGER, `time_total` INTEGER, `time_last` INTEGER, `watched` INTEGER, `view_count` INTEGER, `last_view` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItemStatistic_id_parent` ON `TableItemStatistic` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableItemUrls` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`url` TEXT, `active` INTEGER );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItemUrls_url` ON `TableItemUrls` (`url`);",

                "CREATE TABLE IF NOT EXISTS `TableFavorites` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`title` TEXT, `desc` TEXT, `img` TEXT, `url` TEXT, `vlc_id` INTEGER );",
                "CREATE INDEX IF NOT EXISTS `Index_TableFavorites_title` ON `TableFavorites` (`title`);",

                "CREATE TABLE IF NOT EXISTS `TableItemTitles` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`name` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItemTitles_name` ON `TableItemTitles` (`name`);",

                "CREATE TABLE IF NOT EXISTS `TableItemImages` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`name` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItemImages_name` ON `TableItemImages` (`name`);",

                "CREATE TABLE IF NOT EXISTS `TableItemTrailers` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`name` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItemTrailers_name` ON `TableItemTrailers` (`name`);",


                "CREATE TABLE IF NOT EXISTS `TableItemIds` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`type` TEXT, `val` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableItemIds_id_parent_type` ON `TableItemIds` (`id_parent`, `type`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableItemIds_id_parent` ON `TableItemIds` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableGroupIds` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`type` TEXT, `val` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableGroupIds_id_parent_type` ON `TableGroupIds` (`id_parent`, `type`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableGroupIds_id_parent` ON `TableGroupIds` (`id_parent`);",

                /// Main table to index

                "CREATE TABLE IF NOT EXISTS `TableGenres` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`ele_id` INTEGER, `name` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableGenres_name` ON `TableGenres` (`name`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableGenres_ele_id` ON `TableGenres` (`ele_id`);",

                "CREATE TABLE IF NOT EXISTS `TableProducers` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`ele_id` INTEGER, `name` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableProducers_name` ON `TableProducers` (`name`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableProducers_ele_id` ON `TableProducers` (`ele_id`);",

                "CREATE TABLE IF NOT EXISTS `TableStudios` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`ele_id` INTEGER, `name` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableStudios_name` ON `TableStudios` (`name`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableStudios_ele_id` ON `TableStudios` (`ele_id`);",

                "CREATE TABLE IF NOT EXISTS `TableTags` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`ele_id` INTEGER, `name` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableTags_name` ON `TableTags` (`name`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableTags_ele_id` ON `TableTags` (`ele_id`);",

                "CREATE TABLE IF NOT EXISTS `TableCountry` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`ele_id` INTEGER, `name` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableCountry_name` ON `TableCountry` (`name`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableCountry_ele_id` ON `TableCountry` (`ele_id`);",

                "CREATE TABLE IF NOT EXISTS `TableActors` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`ele_id` INTEGER, `name` TEXT, `role` TEXT, `thumb` TEXT, `profile` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableActors_name` ON `TableActors` (`name`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableActors_ele_id` ON `TableActors` (`ele_id`);",

                /// Indexes

                "CREATE TABLE IF NOT EXISTS `TableActorsIndex` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`idx_id` INTEGER );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableActorsIndex_id_parent_idx_id` ON `TableActorsIndex` (`id_parent`, `idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableActorsIndex_idx_id` ON `TableActorsIndex` (`idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableActorsIndex_id_parent` ON `TableActorsIndex` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableProducersIndex` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`idx_id` INTEGER );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableProducersIndex_id_parent_idx_id` ON `TableProducersIndex` (`id_parent`, `idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableProducersIndex_idx_id` ON `TableProducersIndex` (`idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableProducersIndex_id_parent` ON `TableProducersIndex` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableStudiosIndex` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`idx_id` INTEGER );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableStudiosIndex_id_parent_idx_id` ON `TableStudiosIndex` (`id_parent`, `idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableStudiosIndex_idx_id` ON `TableStudiosIndex` (`idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableStudiosIndex_id_parent` ON `TableStudiosIndex` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableGenresIndex` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`idx_id` INTEGER );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableGenresIndex_id_parent_idx_id` ON `TableGenresIndex` (`id_parent`, `idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableGenresIndex_idx_id` ON `TableGenresIndex` (`idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableGenresIndex_id_parent` ON `TableGenresIndex` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableTagsIndex` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`idx_id` INTEGER );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableTagsIndex_id_parent_idx_id` ON `TableTagsIndex` (`id_parent`, `idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableTagsIndex_idx_id` ON `TableTagsIndex` (`idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableTagsIndex_id_parent` ON `TableTagsIndex` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableCountryIndex` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`idx_id` INTEGER );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableCountryIndex_id_parent_idx_id` ON `TableCountryIndex` (`id_parent`, `idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableCountryIndex_idx_id` ON `TableCountryIndex` (`idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableCountryIndex_id_parent` ON `TableCountryIndex` (`id_parent`);",

                "CREATE TABLE IF NOT EXISTS `TableHistoryIndex` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`idx_id` INTEGER, `play_position` INTEGER, `date_view` TEXT );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableHistoryIndex_id_parent_idx_id` ON `TableHistoryIndex` (`id_parent`, `idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableHistoryIndex_idx_id` ON `TableHistoryIndex` (`idx_id`);",
                "CREATE INDEX IF NOT EXISTS `Index_TableHistoryIndex_id_parent` ON `TableHistoryIndex` (`id_parent`);",

                /// Other

                "CREATE TABLE IF NOT EXISTS `TableEpgList` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER )",

                "CREATE TABLE IF NOT EXISTS `TableEpgItems` (`idx` INTEGER PRIMARY KEY AUTOINCREMENT, `id_parent` INTEGER," +
                        "`title_id` TEXT, `epg_id` TEXT, `title_default` TEXT, `poster_default` TEXT, `change_id` INTEGER DEFAULT 1 );",
                "CREATE UNIQUE INDEX IF NOT EXISTS `Index_TableEpgItems_id_parent_idx_id` ON `TableEpgItems` (`title_id`);",

        };
        public static final String[] BaseDelete = new String[] {
                "DROP TABLE IF EXISTS `TablePlayList`",
                "DROP TABLE IF EXISTS `TableItemTitles`",
                "DROP TABLE IF EXISTS `TableItemImages`",
                "DROP TABLE IF EXISTS `TableItemTrailers`",
                "DROP TABLE IF EXISTS `TableGroups`",
                "DROP TABLE IF EXISTS `TableItems`",
                "DROP TABLE IF EXISTS `TableItemIds`",
                "DROP TABLE IF EXISTS `TableGroupIds`",
                "DROP TABLE IF EXISTS `TableGenres`",
                "DROP TABLE IF EXISTS `TableProducers`",
                "DROP TABLE IF EXISTS `TableStudios`",
                "DROP TABLE IF EXISTS `TableTags`",
                "DROP TABLE IF EXISTS `TableCountry`",
                "DROP TABLE IF EXISTS `TableActors`",
                "DROP TABLE IF EXISTS `TableActorsIndex`",
                "DROP TABLE IF EXISTS `TableProducersIndex`",
                "DROP TABLE IF EXISTS `TableStudiosIndex`",
                "DROP TABLE IF EXISTS `TableGenresIndex`",
                "DROP TABLE IF EXISTS `TableTagsIndex`",
                "DROP TABLE IF EXISTS `TableCountryIndex`",
                "DROP TABLE IF EXISTS `TableItemStatistic`",
                "DROP INDEX IF EXISTS `Index_TableGroups_nfo`",
                "DROP INDEX IF EXISTS `Index_TableGroups_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableGroups_nfo`",
                "DROP INDEX IF EXISTS `Index_TableItems_uri`",
                "DROP INDEX IF EXISTS `Index_TableItems_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableItemStatistic_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableItemTitles_name`",
                "DROP INDEX IF EXISTS `Index_TableItemImages_name`",
                "DROP INDEX IF EXISTS `Index_TableItemTrailers_name`",
                "DROP INDEX IF EXISTS `Index_TableItemIds_id_parent_type`",
                "DROP INDEX IF EXISTS `Index_TableItemIds_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableGroupIds_id_parent_type`",
                "DROP INDEX IF EXISTS `Index_TableGroupIds_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableGenres_name`",
                "DROP INDEX IF EXISTS `Index_TableGenres_ele_id`",
                "DROP INDEX IF EXISTS `Index_TableProducers_name`",
                "DROP INDEX IF EXISTS `Index_TableProducers_ele_id`",
                "DROP INDEX IF EXISTS `Index_TableStudios_name`",
                "DROP INDEX IF EXISTS `Index_TableStudios_ele_id`",
                "DROP INDEX IF EXISTS `Index_TableTags_name`",
                "DROP INDEX IF EXISTS `Index_TableTags_ele_id`",
                "DROP INDEX IF EXISTS `Index_TableCountry_name`",
                "DROP INDEX IF EXISTS `Index_TableCountry_ele_id`",
                "DROP INDEX IF EXISTS `Index_TableActors_name`",
                "DROP INDEX IF EXISTS `Index_TableActors_ele_id`",
                "DROP INDEX IF EXISTS `Index_TableActorsIndex_id_parent_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableActorsIndex_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableActorsIndex_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableProducersIndex_id_parent_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableProducersIndex_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableProducersIndex_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableStudiosIndex_id_parent_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableStudiosIndex_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableStudiosIndex_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableGenresIndex_id_parent_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableGenresIndex_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableGenresIndex_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableTagsIndex_id_parent_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableTagsIndex_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableTagsIndex_id_parent`",
                "DROP INDEX IF EXISTS `Index_TableCountryIndex_id_parent_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableCountryIndex_idx_id`",
                "DROP INDEX IF EXISTS `Index_TableCountryIndex_id_parent`"
        };
        public static final String BaseCheckEmpty = "SELECT (SELECT COUNT(*) FROM `TableGroups`) AS `count_group`, (SELECT COUNT(*) FROM `TableItems`) AS `count_item`;";
        public static final String[] BaseUpdateOnCreate = new String[] {
                "INSERT INTO `main`.`TableEpgList` (`id_parent`) VALUES ('0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'Ю', 'Ю', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ШОКИРУЮЩЕЕ', 'Шокирующее', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ШАНСОН ТВ', 'Шансон_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЧЕ', 'Че', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЧЕ!', 'Че', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ФЕНИКС КИНО', 'Феникс_Кино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'УСАДЬБА ТВ', 'Усадьба', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'УСАДЬБА', 'Усадьба', 'УСАДЬБА ТВ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТОЧКА ОТРЫВА', 'Точка_отрыва', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТНОМЕР', 'Тномер', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТЕЛЕПУТЕШЕСТВИЯ', 'Телепутешествия', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТЕАТР', 'Театр', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТНТ MUSIC', 'ТНТ_Music', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТНТ4', 'ТНТ4', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТНТ', 'ТНТ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТЕТ', 'ТЕТ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТДК', 'ТДК', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТВ ЦЕНТР', 'ТВ_Центр', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТВЦ', 'ТВ_Центр', 'ТВ ЦЕНТР', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ТВ-3', 'ТВ-3', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СУПЕР', 'Супер', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СТРАШНОЕ', 'Страшное_HD', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СПАС', 'Спас_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СОНЦЕ', 'Солнце', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СМАЙЛИК ТВ', 'Смайлик_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СКАЗКИ ЗАЙКИ', 'Сказки_Зайки', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СТС LOVE', 'СТС_Love', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СТС', 'СТС', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СТРК', 'СТРК', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'СТВ', 'СТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РЫЖИЙ', 'Рыжий', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РУССКИЙ РОМАН', 'Русский_роман', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РУССКИЙ ДЕТЕКТИВ', 'Русский_детектив', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РУССКИЙ БЕСТСЕЛЛЕР', 'Русский_бестселлер', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РУССКИЙ ИЛЛЮЗИОН', 'Русский_Иллюзион', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РУССКАЯ КОМЕДИЯ', 'Русская_Комедия', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РОССИЯ 24', 'Россия_24', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РОССИЯ 1', 'Россия_1', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РОДНОЕ КИНО', 'Родное_кино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РЕТРО', 'Ретро_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РЖД ТВ', 'РЖД', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РЕН ТВ', 'РЕН_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РБК ТВ', 'РБК', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПЯТЫЙ КАНАЛ', 'Пятый_Канал', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПЯТНИЦА!', 'Пятница', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПЯТНИЦА', 'Пятница', 'ПЯТНИЦА!', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПОЕХАЛИ!', 'Поехали!', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПОБЕДА', 'Победа', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПЕРВЫЙ ОБРАЗОВАТЕЛЬНЫЙ', 'Первый_образовательный', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПЕРВЫЙ КАНАЛ `ЕВРАЗИЯ`', 'Первый_канал_Евразия', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПЕРВЫЙ КАНАЛ', 'Первый_канал', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПЕРВЫЙ ВЕГЕТАРИАНСКИЙ', 'Первый_вегетарианский', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ПЕРВЫЙ ТУЛЬСКИЙ', 'Первый_Тульский', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ОХОТНИК И РЫБОЛОВ', 'Охотник_и_рыболов', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ОХОТА И РЫБАЛКА', 'Охота_и_рыбалка', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ОТКРЫТЫЙ МИР', 'Открытый_Мир', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ОСТРОСЮЖЕТНОЕ', 'Остросюжетное_HD', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ОТР', 'ОТР', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ОТВ24', 'ОТВ_-_Областное_телевидение', 'ОБЛАСТНОЕ ТЕЛЕВИДЕНИЕ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ОНТ', 'ОНТ_(Беларусь)', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'О!КИНО', 'О!Кино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'О!', 'О!', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НОСТАЛЬГИЯ', 'Ностальгия', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НОВЫЙ МИР', 'Новый_мир', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НАШЕ ТВ', 'Наше_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НАШ', 'Наше_ТВ', 'НАШЕ ТВ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НАШЕ НОВОЕ КИНО', 'Наше_Новое_Кино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НАШЕ ЛЮБИМОЕ КИНО', 'Наше_Любимое', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НАУКА 2.0', 'Наука_2_0', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НАСТОЯЩЕЕ СТРАШНОЕ ТВ', 'Настоящее_Страшное_Телевидение', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'NANO TV', 'Нано', 'НАНО ТВ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НАНО ТВ', 'Нано', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НТН', 'НТН_(Украина)', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НТВ ХИТ', 'НТВ_Хит', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НТВ СТИЛЬ', 'НТВ_Стиль', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НТВ СЕРИАЛ', 'НТВ_Сериал', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НТВ ПРАВО', 'НТВ_Право', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НТВ-ПРАВО', 'НТВ_Право', 'НТВ ПРАВО', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'НТВ', 'НТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ННТВ', 'ННТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МУЛЬТИМУЗЫКА', 'Мультимузыка', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МУЛЬТИЛАНДИЯ', 'Мультиландия', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МУЛЬТ', 'Мульт', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МУЗЫКА ПЕРВОГО', 'Музыка_Первого', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МУЗСОЮЗ', 'МузСоюз', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МУЖСКОЕ КИНО', 'Мужское_кино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МОЯ ПЛАНЕТА', 'Моя_Планета', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МОСКВА 24', 'Москва-24', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МИР БЕЛОГОРЬЯ', 'Мир_Белогорья', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МУЗ ТВ', 'МУЗ-ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МИР PREMIUM', 'МИР_HD', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МИР 24', 'МИР_24', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МИР', 'МИР', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЛДПР ТВ', 'ЛДПР_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КУХНЯ ТВ', 'Кухня_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'РОССИЯ К', 'Культура', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КРИК ТВ', 'Крик_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КРАСНАЯ ЛИНИЯ ТВ', 'Красная_линия', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КРАСНАЯ ЛИНИЯ', 'Красная_линия', 'КРАСНАЯ ЛИНИЯ ТВ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОХИТ', 'Кинохит', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОУЖАС', 'Киноужас', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОСЕМЬЯ', 'Киносемья', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНО СЕМЬЯ', 'Киносемья', 'КИНОСЕМЬЯ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОСВИДАНИЕ', 'Киносвидание', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНО СВИДАНИЕ', 'Киносвидание', 'КИНОСВИДАНИЕ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОПРЕМЬЕРА', 'Кинопремьера', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОПРЕМИУМ', 'Кинопремиум_HD', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОПОКАЗ', 'Кинопоказ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОМИКС', 'Киномикс', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОКОМЕДИЯ', 'Кинокомедия', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНО ТВ', 'Кино_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КАРУСЕЛЬ', 'Карусель', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КАНАЛ DISNEY', 'Канал_Disney', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', '2X2', 'Канал_2x2', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', '1+1', 'Канал_1_1', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КАЛЕЙДОСКОП ТВ', 'Калейдоскоп_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КИНОСЕРИЯ', 'КИНОСЕРИЯ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'КВН ТВ', 'КВН_ТВ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'К2', 'К2', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'К1', 'К1', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ИСТОРИЯ', 'История', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ИНТЕР', 'Интер', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ИНДИЙСКОЕ КИНО', 'Индийское_кино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ИЛЛЮЗИОН+', 'Иллюзион__', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ИЗВЕСТИЯ', 'Известия', 'ИЗВЕСТИЯ ТВ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ИЗВЕСТИЯ ТВ', 'Известия', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЗДОРОВЬЕ', 'Здоровье', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЗВЕЗДА', 'Звезда', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЗАГОРОДНАЯ ЖИЗНЬ', 'Загородная_жизнь', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЖИВИ!', 'Живи!', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЖИВАЯ ПЛАНЕТА', 'Живая_планета', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЕНИСЕЙ', 'Енисей_регион', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЕВРОНОВОСТИ', 'Евроновости', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ЕВРОКИНО', 'Еврокино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ДОН 24', 'Дон24', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ДОМАШНИЙ', 'Домашний', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ДОМ КИНО', 'Дом_кино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ДОМ КИНО ПРЕМИУМ', 'Дом_Кино_Премиум', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ДОЖДЬ', 'Дождь', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ВРЕМЯ', 'ВРЕМЯ', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'БЕЛАРУСЬ 4', 'Беларусь_24', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'АВТО ПЛЮС', 'Авто_Плюс', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'АВТО 24', 'Авто24_HD', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ZEE-TV', 'Zee_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'WORLD FASHION CHANNEL РОССИЯ', 'World_Fashion_Channel_(рус_)', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VIASAT SPORT', 'Viasat_Sport', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VIASAT NATURE', 'Viasat_Nature_CEE', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VIASAT HISTORY', 'Viasat_History', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VIASAT EXPLORE', 'Viasat_Explore', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VIP SERIAL', 'ViP_Serial', 'VIP СЕРИАЛЫ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VIP PREMIERE', 'ViP_Premiere', 'VIP ПРЕМЬЕРА', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VIP MEGAHIT', 'ViP_Megahit', 'VIP МЕГА-ХИТ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VIP COMEDY', 'ViP_Comedy', 'VIP КОМЕДИЯ', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'VH1 CLASSIC', 'VH1_Classic', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'UNIVER TV', 'Universmotri_ru', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ULTRA HD CINEMA', 'Ultra_HD_Cinema', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TRAVEL CHANNEL', 'Travel_Channel', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TRAVEL + ADVENTURE', 'Travel_Adventure', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TV XXI', 'TV_XXI', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TVM CHANNEL', 'TVM_Channel', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TV 5', 'TV5-Monde', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TV1000 РУССКОЕ КИНО', 'TV1000_Русское_кино', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TV1000 ACTION', 'TV1000_Action', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TV1000', 'TV1000', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'TLC', 'TLC', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'STAR MEDIA', 'Star_Family', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'SPIKE', 'Spike', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'SONY TURBO', 'Sony_Turbo', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'SHOT TV', 'Shot_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'SONY SCI-FI', 'SONY_Sci-Fi', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'RUSSIAN MUSICBOX', 'Russian_MusicBox', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'RU.TV', 'RU_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'RTG', 'RTG_HD', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'PARAMOUNT COMEDY', 'Paramount_Comedy', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'PARAMOUNT CHANNEL', 'Paramount_Channel', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'OUTDOOR CHANNEL', 'Outdoor_Channel', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'OCEAN TV', 'Ocean_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'NICKELODEON', 'Nickelodeon', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'NICK JR.', 'Nick_Jr', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'NATIONAL GEOGRAPHIC', 'National_Geographic', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'NATIONAL GEOGRAPHIC WILD', 'Nat_Geo_WILD', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'MUSICBOX GOLD', 'MUSIC_Box_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'МТВ', 'MTV_Россия', 'MTV', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'MTV', 'MTV_Россия', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'MTV ROCKS', 'MTV_Rocks', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'MTV HITS', 'MTV_Hits', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'MTV DANCE', 'MTV_Dance', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'M-1 GLOBAL', 'M-1_GLOBAL', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'LUXURY', 'Luxury', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'JIMJAM', 'JimJam', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'INVESTIGATION DISCOVERY', 'ID_Investigation_Discovery', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ICTV', 'ICTV_(Украина)', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'HOLLYWOOD', 'Hollywood', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'HD MEDIA', 'HD_Media', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'FOX LIFE', 'Fox_Life', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'FOX', 'Fox', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'WORLD FASHION CHANNEL', 'Fashion_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'FASHION TV', 'Fashion_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'FAN', 'FAN', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'EXTREME SPORTS', 'Extreme_Sports', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'EUROSPORT 2', 'Eurosport_2', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'EUROSPORT 4K', 'Eurosport_1_HD', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'EUROSPORT 1', 'Eurosport_1', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ENGLISH CLUB', 'English_Club_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'DISCOVERY SCIENCE', 'Discovery_Science', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'DISCOVERY', 'Discovery_HD', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'DISCOVERY CHANNEL', 'Discovery_Channel', 'DISCOVERY', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'DEUTSCHE WELLE', 'Deutsche_Welle', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'DA VINCI', 'Da_Vinci', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'DTX', 'DTX', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'CINEMA', 'Cinema', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'CARTOON NETWORK', 'Cartoon_Network', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'CNN INTERNATIONAL', 'CNN_International', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'CCTV4', 'CCTV-Русский', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'BRIDGE TV CLASSIC', 'Bridge_TV_Classic', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'BRIDGE TV', 'Bridge_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'BOOMERANG', 'Boomerang', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'БОЛТ', 'Bolt', '', '', '0');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'BOLLYWOOD', 'Bollywood_HD', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'BABY TV', 'Baby_TV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'BTV', 'BTV', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'BRIDGE TV РУССКИЙ ХИТ', 'BRIDGE_TV_Русский_Хит', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'BRIDGE TV HITS', 'BRIDGE_TV_Dance', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ANIMAL PLANET', 'Animal_Planet', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'ANI', 'Ani', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'AMEDIA PREMIUM', 'Amedia_Premium', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'AMEDIA 2', 'Amedia_Hit', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'A2', 'A2', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', '8 КАНАЛ', '8_Канал', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', '5 КАНАЛ', '5_канал_(Украина)', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', 'T24', '24_Техно', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', '1', '1HD', '', '', '');",
                "INSERT INTO `main`.`TableEpgItems` (`id_parent`, `title_id`, `epg_id`, `title_default`, `poster_default`, `change_id`) VALUES ('1', '112 УКРАИНА', '112_Украина', '', '', '');",
        };
}
