theme: jekyll-theme-hacker
show_downloads: true
title: VLC Android-TV Remote
description: This Application is designed to control the VLC player running on a remote device from the Android-TV remote control. Support Android-TV only.

github:
  apk_url: https://github.com/CloneTV/VLC-TV-Remote/releases/download/1.1/avlctv-remote-release.apk
  addon_url: https://github.com/CloneTV/VLC-TV-Remote/releases/download/1.1/VLCAddOnMediaPlayList.exe
