theme: jekyll-theme-hacker

github:
  apk_url: https://github.com/CloneTV/VLC-TV-Remote/releases/download/1.0/avlctv-remote-release.apk
  addon_url: https://github.com/CloneTV/VLC-TV-Remote/releases/download/1.0/VLCAddOnMediaPlayList.exe
